### ISSUE TITLE
Bug: Copy-pasting AUR package name into search field does not work

### ISSUE THREAD

**Issue by CommanderRedYT** [Lukas-Heiligenbrunner/AURCache#15] opened 2024-06-25 07:36 UTC
When copy-pasting a string into the searchfield, a empty list shows up. If you type every character manually, it works. (Removing one character and adding it again does not work either.

**Comment by Lukas-Heiligenbrunner** [comment] 2024-06-25 19:53
Hey, 
I can't reproduce this one, what exactly are you searching? And on the AUR page right, not on the main dashboard?

**Comment by CommanderRedYT** [comment] 2024-06-25 20:10
Yes, on the AUR page. I just copy-paste any full package name like `yay` into the field. It looks like there are two input fields ontop of each other. But it shows no results. When I enter `y` `a` `y` it works.

**Comment by Lukas-Heiligenbrunner** [comment] 2024-06-25 20:39
https://github.com/Lukas-Heiligenbrunner/AURCache/assets/30468956/19d904c5-7159-4f27-917d-7330ee5f7ed3

Like this?

**Comment by Lukas-Heiligenbrunner** [comment] 2024-06-25 20:41
You could also check if the request to `/api/search?query=yay` is successfull

**Comment by CupricReki** [comment] 2024-09-02 14:46
Can't reproduce this either.

**Comment by Lukas-Heiligenbrunner** [comment] 2024-09-09 05:41
Since @CommanderRedYT doesn't reply and I can't reproduce this I'll close the issue.

**Closed by Lukas-Heiligenbrunner** 2024-09-09 05:41 UTC
Labels: help wanted
